// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountsService backs Preferences > Accounts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Remove(userID: string): $CancellablePromise<void> {
    return $Call.ByID(2419645974, userID);
}

export function State(): $CancellablePromise<$models.AccountsView> {
    return $Call.ByID(2500348535);
}

export function Switch(userID: string): $CancellablePromise<void> {
    return $Call.ByID(3371319002, userID);
}
