// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginService backs the add-account sheet in Preferences > Accounts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Back(): $CancellablePromise<void> {
    return $Call.ByID(1745871942);
}

/**
 * Close ends the sheet's session, cancelling a login that hasn't finished.
 */
export function Close(session: number): $CancellablePromise<void> {
    return $Call.ByID(2223846471, session);
}

export function CopyCode(): $CancellablePromise<void> {
    return $Call.ByID(3994438213);
}

/**
 * Open starts a session for a newly shown sheet; renewHostname is the server
 * of an account to log in to again, or "" to add an account.
 */
export function Open(renewHostname: string): $CancellablePromise<$models.LoginView> {
    return $Call.ByID(1314043317, renewHostname);
}

export function OpenBrowser(): $CancellablePromise<void> {
    return $Call.ByID(2137946303);
}

export function Start(hostname: string): $CancellablePromise<void> {
    return $Call.ByID(2568739179, hostname);
}

export function State(): $CancellablePromise<$models.LoginView> {
    return $Call.ByID(2349644394);
}
