// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginService backs the login window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Back(): $CancellablePromise<void> {
    return $Call.ByID(1745871942);
}

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(334155495);
}

export function ChooseCloud(): $CancellablePromise<void> {
    return $Call.ByID(3691013221);
}

export function ChooseSelfHosted(): $CancellablePromise<void> {
    return $Call.ByID(2304610489);
}

export function CopyCode(): $CancellablePromise<void> {
    return $Call.ByID(3994438213);
}

export function Login(): $CancellablePromise<void> {
    return $Call.ByID(3240949102);
}

export function OpenBrowser(): $CancellablePromise<void> {
    return $Call.ByID(2137946303);
}

export function SetURL(u: string): $CancellablePromise<void> {
    return $Call.ByID(2160852472, u);
}

export function State(): $CancellablePromise<$models.LoginView> {
    return $Call.ByID(2349644394);
}
