// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogsService backs the Logs tab.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(265640890);
}

export function Copy(seqs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1438040892, seqs);
}

export function Export(): $CancellablePromise<void> {
    return $Call.ByID(1903958827);
}

export function Snapshot(): $CancellablePromise<$models.LogsSnapshot> {
    return $Call.ByID(4260106421);
}
