// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo is static information shown in the About tab.
 */
export interface AppInfo {
    "version": string;
    "year": number;
}

/**
 * LogEntry is a log line as sent to the Logs tab. Seq increases with every
 * line read, so the frontend can drop appends it already has.
 */
export interface LogEntry {
    "seq": number;
    "stamp": string;
    "level": string;
    "line": string;
}

/**
 * LoginView is what the login window renders.
 */
export interface LoginView {
    "stage": string;
    "selfHostedUrl": string;
    "code": string;
    "manualUrl": string;
    "showBack": boolean;
    "backEnabled": boolean;
    "showLogin": boolean;
    "loginEnabled": boolean;
}

/**
 * LogsSnapshot replaces everything shown in the Logs tab.
 */
export interface LogsSnapshot {
    "entries": LogEntry[] | null;
}

/**
 * MenuItem is one row of the tray popup. Only visible items are included.
 */
export interface MenuItem {
    "id": string;
    "kind": string;
    "label": string;
    "enabled": boolean;
    "checked": boolean;

    /**
     * Checkable reserves the leading check column, so checked and unchecked rows line up.
     */
    "checkable": boolean;

    /**
     * Loading shows a small spinner: in the check column of a checkable row,
     * otherwise trailing the label.
     */
    "loading": boolean;

    /**
     * Dot is a status dot color shown before the label.
     */
    "dot": string;

    /**
     * Icon is shown before a label's text.
     */
    "icon": string;

    /**
     * Inset indents a header to line up with the text of checkable rows.
     */
    "inset": boolean;

    /**
     * Value is the right-hand text of a detail row.
     */
    "value": string;
    "items"?: MenuItem[] | null;
}

/**
 * MenuState is the full tray popup contents.
 */
export interface MenuState {
    "items": MenuItem[] | null;

    /**
     * Loading replaces the whole panel with a spinner, as the macOS menu does
     * while starting up and while switching accounts or organizations.
     */
    "loading": boolean;
}

/**
 * PrefsOpened is sent to the preferences window each time it is shown.
 */
export interface PrefsOpened {
    "tab": number;
    "settings": Settings;
}

/**
 * Settings is the Preferences tab form.
 */
export interface Settings {
    "openAtLogin": boolean;
    "autoConnect": boolean;
    "dnsOverride": boolean;
    "dnsTunnel": boolean;
    "primaryDns": string;
    "secondaryDns": string;
    "mtu": string;
    "exitNodeTakesPrecedence": boolean;

    /**
     * Disabled is set when an administrator has turned off user settings.
     */
    "disabled": boolean;
}

/**
 * SettingsResult is the outcome of applying a settings change. On a
 * validation error nothing is saved and Field names the invalid field
 * ("mtu", "primaryDns" or "secondaryDns") so the sheet can show Error inline.
 */
export interface SettingsResult {
    "settings": Settings;
    "field": string;
    "error": string;
}

/**
 * StatusSite is one row of the Sites list in the Status tab.
 */
export interface StatusSite {
    "id": number;
    "name": string;
    "endpoint": string;
    "status": string;
    "color": string;

    /**
     * Connection is "Local", "Relay" or "Direct"; empty for the Pangolin Server row.
     */
    "connection": string;

    /**
     * LastSeen is an RFC 3339 time, or empty when unknown.
     */
    "lastSeen": string;

    /**
     * Gateway is true when the site is one of those currently used as the exit
     * node (gateway) that all traffic is routed through.
     */
    "gateway": boolean;
}

/**
 * StatusView is everything the Status tab renders.
 */
export interface StatusView {
    "stateText": string;
    "color": string;
    "version": string;
    "agent": string;
    "orgId": string;

    /**
     * Gateway summarizes the exit node: "Off", or "Active (resource N)".
     */
    "gateway": string;
    "sites": StatusSite[] | null;
    "json": string;
}

/**
 * TrayLayout tells the popup which side submenus open on and which edge the
 * menu is anchored to.
 */
export interface TrayLayout {
    /**
     * "left" or "right"
     */
    "submenuSide": string;

    /**
     * "top" or "bottom"
     */
    "anchor": string;
    "panelWidth": number;
    "padding": number;
}
