// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OnboardingService backs the setup window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1050728817);
}

export function MarkPrivacyAcknowledged(): $CancellablePromise<void> {
    return $Call.ByID(1750977286);
}

export function MarkWelcomeSeen(): $CancellablePromise<void> {
    return $Call.ByID(3515793657);
}

export function State(): $CancellablePromise<$models.OnboardingState> {
    return $Call.ByID(1728806924);
}
