// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PreferencesService backs the Preferences tab.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Opened(): $CancellablePromise<$models.PrefsOpened> {
    return $Call.ByID(1409912611);
}

export function Update(form: $models.Settings): $CancellablePromise<$models.SettingsResult> {
    return $Call.ByID(2264599907, form);
}
