// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService backs the update window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Check(): $CancellablePromise<void> {
    return $Call.ByID(3003416057);
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(357839405);
}

export function Install(): $CancellablePromise<void> {
    return $Call.ByID(1087739310);
}

export function State(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2946705016);
}
